#page title
page_title                                :  Plum Village Songs - From Sangha for Sangha                                        # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                :                                 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : vn                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://apps.apple.com/us/app/app-store-connect/id1234793120?platform=iphone                                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=app.plumvillagesongs                                          # Enter Google Play Store URL.
presskit_download_link                    : #https://plumvillagesong.app                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon3.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
favicon                                   : assets/appicon3.ico
app_url                                   : https://www.plumvillagesong.app 
app_name                                  : Thiền Ca Làng Mai                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_header_name                           : assets/plumvillage.png
app_price                                 : Miễn phí                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Thiền ca là những bài hát có công năng nuôi dưỡng chánh niệm và làm lớn lên hạnh phúc cho người thực tập. Những bài hát nào khi hát lên ta cảm thấy thân tâm khỏe nhẹ, an lành và giúp ta trở về tiếp xúc với sự sống mầu nhiệm thì đều được gọi là thiền ca. 


enable_smart_app_banner                   : false                                      # Set to true to show a smart app banner at top of page on mobile devices.

app_keywords                              : mindfulness song, practice song, thiền ca, thiền ca Làng Mai, Plum village song, thien ca lang mai 

# Information About Yourself
your_name                                 : Plum Village Music Team                               
your_link                                 : https://www.plumvillagesong.app                    
your_city                                 : Thái Lan                                
email_address                             : pvsongs@plumvillage.org
facebook_username                         : #plumvillagesongs                            
instagram_username                        : #plumvillagesongs
twitter_username                          : #plumvillagesongs
github_username                           : #plumvillagesongs
youtube_username                          : #plumvillagesongs



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : + 200 bài thiền ca
    description                           : Dưới nhiều ngôn ngữ khác nhau như Tiếng Việt, Tiếng Anh, Tiếng Thái
    fontawesome_icon_name                 : magic
    
  - title                                 : Cùng hát thiền ca trong các buổi sinh hoạt Tăng thân
    description                           : Lời bài hát cùng với hợp âm và music sheet 
    fontawesome_icon_name                 : mobile

  - title                                 : Nghe thiền ca
    description                           : Phát các bài thiền ca 
    fontawesome_icon_name                 : play-circle

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.9

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
